services:
  gm-general-chat:
    build: .
    container_name: gm-general-chat
    expose:
      - "7005"
    ports:
      - "7005:7005"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-general:6379/0
      - DEFAULT_PROVIDER=openai
    networks:
      - gomedisys-net
    depends_on:
      - redis-general
    volumes:
      - ./logs:/app/logs
      - .:/app
    restart: always


  redis-general:
    image: redis/redis-stack-server:latest
    container_name: redis-general
    networks:
      - gomedisys-net
    restart: always

networks:
  gomedisys-net:
    external: true